version: '3'
services:
  postgres:
    build: ./postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./postgres/.env
  pgadmin: 
    image: dpage/pgadmin4:6.19
    restart: always
    ports:
      - 8080:80
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=test
      - PGADMIN_CONFIG_SERVER_MODE=False
      - STRICT_TRANSPORT_SECURITY_ENABLED=False
      - PGADMIN_CONFIG_PROXY_X_HOST_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT=1
volumes:
  minio-data:
  postgres-data: