version: '3'
services:
  postgres:
    build: ./postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./postgres/.env
volumes:
  minio-data:
  postgres-data: